import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const roboto = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WhatBytes Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} flex min-h-dvh flex-col antialiased`}
      >
        <Header />
        <main className="flex flex-1 gap-8">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
